# Generated by Django 6.0.7 on 2026-07-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=50)),
                ('row_identifier', models.CharField(max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=50)),
                ('raw_value', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=20, unique=True)),
                ('org_id', models.CharField(db_index=True, max_length=20)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=30, unique=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('category_code', models.CharField(blank=True, max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=20)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_a_records', to='reconciliation.location')),
            ],
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=30, unique=True)),
                ('record_ref_raw', models.CharField(max_length=50)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('value_raw', models.CharField(blank=True, max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_b_entries', to='reconciliation.location')),
                ('record_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_b_entries', to='reconciliation.systemarecord')),
            ],
        ),
        migrations.CreateModel(
            name='Disagreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('MISSING_IN_B', 'Missing in System B'), ('ORPHAN_IN_B', 'Orphan in System B (no matching System A record)'), ('DUPLICATE_IN_B', 'Duplicate in System B'), ('VALUE_MISMATCH', 'Value mismatch between systems'), ('UNPARSEABLE_VALUE', 'System B value could not be parsed')], db_index=True, max_length=30)),
                ('value_a', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_b', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_b_raw', models.CharField(blank=True, max_length=50)),
                ('record_id_a', models.CharField(blank=True, max_length=30)),
                ('entry_id_b', models.CharField(blank=True, max_length=30)),
                ('record_ref_raw', models.CharField(blank=True, max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reconciliation.location')),
                ('record_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reconciliation.systemarecord')),
                ('entry_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reconciliation.systembentry')),
            ],
            options={
                'ordering': ['reason', 'record_id_a'],
            },
        ),
    ]
