# Generated by Django 6.0.7 on 2026-07-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_add_extra_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='importissue',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
